### PR TITLE
enable the 'relax' param to better handle ambiguously encoded/escaped CSV files

### PR DESCRIPTION
**Pull request by missinglink**
This PR is a replacement for https://github.com/pelias/transit/pull/43 with a semantic release commit message and rebased against master to remove the merge commit.

closes https://github.com/pelias/transit/pull/43

### CODE REVIEW

**Comment by missinglink** [comment]
The following docker images have been generated for testing:
- https://hub.docker.com/layers/pelias/transit/stefanocudini-2020-10-14-51015851b4136913160421c37578c7a7f59b17b4/images/sha256-3fb860c44ba356ce61bc61d7be4db9c3a4aa92d603709f961e453f89bca003fb?context=explore
- https://hub.docker.com/layers/pelias/transit/stefanocudini/images/sha256-3fb860c44ba356ce61bc61d7be4db9c3a4aa92d603709f961e453f89bca003fb?context=explore

**Comment by missinglink** [comment]
I tested this against the `portland-metro` project on a clean index and it still works fine with the `relax` setting:

```bash
pelias elastic stats
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 8246,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "sources" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : "transit",
          "doc_count" : 8246,
          "layers" : {
            "doc_count_error_upper_bound" : 0,
            "sum_other_doc_count" : 0,
            "buckets" : [
              {
                "key" : "stops",
                "doc_count" : 8086
              },
              {
                "key" : "bikeshare",
                "doc_count" : 160
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by missinglink** [comment]
Travis is broken again, I've tested this locally and it's working.

Screenshot 2020-10-14 at 13 17 29

**Comment by missinglink** [comment]
https://travis-ci.org/github/pelias/transit/builds/735689691

**Comment by missinglink** [comment]
https://github.com/pelias/transit/releases/tag/v2.2.3

**Comment by missinglink** [comment]
https://hub.docker.com/layers/pelias/transit/master-2020-10-14-570574c6efb4b881569d9e9bc196a95f3cc802b2/images/sha256-c8ac6d8bba5ec1764a28c8c5a668c4a2df03bfd39bc1034a4652e45723be3c61?context=explore

**Comment by stefanocudini** [comment]
I think that relax options enabled is veru useul, I know the environment of opendata and I think that
most gtfs data providers in the world build data in a non-perfectly standard way according to rfc.
There is a need for some flexibility in data pasing..

**Pull request merged**
